/**
 * @file platforms.hpp
 * Detects the platforms and defines several symbols.
 *
 * <h3>Window System</h3>
 * Checked by @c ASCENSION_SUPPORTS_WINDOW_SYSTEM and @c ASCENSION_SELECTS_WINDOW_SYSTEM macros.
 * <table>
 *   <tr><th>Window System</th><th>Symbol</th><th>Notes</th></tr>
 *   <tr><td>GTK3+ (gtkmm 3.x)</td><td>@c ASCENSION_WINDOW_SYSTEM_GTK</td></tr>
 *   <tr><td>Quartz Compositor of Mac OS X</td><td>@c ASCENSION_WINDOW_SYSTEM_QUARTZ</td><td>Default if @c BOOST_OS_MACOS is defined</td></tr>
 *   <tr><td>Nokia Qt</td><td>@c ASCENSION_WINDOW_SYSTEM_QT</td></tr>
 *   <tr><td>Windows Win32</td><td>@c ASCENSION_WINDOW_SYSTEM_WIN32</td><td>Default if @c BOOST_OS_WINDOWS is defined</td></tr>
 *   <tr><td>X Window System</td><td>@c ASCENSION_WINDOW_SYSTEM_X</td></tr>
 * </table>
 *
 * <h3>Graphics System</h3>
 * Checked by @c ASCENSION_SUPPORTS_GRAPHICS_SYSTEM and @c ASCENSION_SELECTS_GRAPHICS_SYSTEM macros.
 * <table>
 *   <tr><th>Graphics System</th><th>Symbol</th><th>Notes</th></tr>
 *   <tr><td>Cairo</td><td>@c ASCENSION_GRAPHICS_SYSTEM_CAIRO</td><td>Default if @c ASCENSION_SELECTS_WINDOW_SYSTEM(GTK)</td></tr>
 *   <tr><td>Mac OS X Core Graphics</td><td>@c ASCENSION_GRAPHICS_SYSTEM_CORE_GRAPHICS</td><td>Default if @c ASCENSION_SELECTS_WINDOW_SYSTEM(QUARTZ)</td></tr>
 *   <tr><td>Windows Direct2D</td><td>@c ASCENSION_GRAPHICS_SYSTEM_DIRECT2D</td><td></td></tr>
 *   <tr><td>Nokia Qt</td><td>@c ASCENSION_GRAPHICS_SYSTEM_QT</td><td>Default if @c ASCENSION_SELECTS_WINDOW_SYSTEM(QT)</td></tr>
 *   <tr><td>Windows GDI</td><td>@c ASCENSION_GRAPHICS_SYSTEM_WIN32_GDI</td><td>Default if @c ASCENSION_SELECTS_WINDOW_SYSTEM(WIN32)</td></tr>
 *   <tr><td>Windows GDI+</td><td>@c ASCENSION_GRAPHICS_SYSTEM_WIN32_GDIPLUS</td><td></td></tr>
 * </table>
 *
 * <h3>Text/Glyph Shaping Engine</h3>
 * Checked by @c ASCENSION_SUPPORTS_SHAPING_ENGINE and @c ASCENSION_SELECTS_SHAPING_ENGINE macros.
 * <table>
 *   <tr><th>Shaping Engine</th><th>Symbol</th><th>Notes</th></tr>
 *   <tr><td>Mac OS X Core Graphics</td><td>@c ASCENSION_SHAPING_ENGINE_CORE_GRAPHICS</td><td></td></tr>
 *   <tr><td>Mac OS X Core Text</td><td>@c ASCENSION_SHAPING_ENGINE_CORE_TEXT</td><td>Default if @c ASCENSION_SELECTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)</td></tr>
 *   <tr><td>Windows DirectWrite</td><td>@c ASCENSION_SHAPING_ENGINE_DIRECT_WRITE</td><td></td></tr>
 *   <tr><td>HarfBuzz</td><td>@c ASCENSION_SHAPING_ENGINE_HARF_BUZZ</td><td></td></tr>
 *   <tr><td>Pango</td><td>@c ASCENSION_SHAPING_ENGINE_PANGO</td><td>Default if @c ASCENSION_SELECTS_GRAPHICS_SYSTEM(CAIRO)</td></tr>
 *   <tr><td>Nokia Qt</td><td>@c ASCENSION_SHAPING_ENGINE_QT</td><td>Default if @c ASCENSION_SELECTS_GRAPHICS_SYSTEM(QT)</td></tr>
 *   <tr><td>Windows Uniscribe</td><td>@c ASCENSION_SHAPING_ENGINE_UNISCRIBE</td><td>Default if @c ASCENSION_SELECTS_GRAPHICS_SYSTEM(WIN32_GDI)</td></tr>
 *   <tr><td>Windows GDI</td><td>@c ASCENSION_SHAPING_ENGINE_WIN32_GDI</td><td></td></tr>
 *   <tr><td>Windows GDI+</td><td>@c ASCENSION_SHAPING_ENGINE_WIN32_GDIPLUS</td><td></td></tr>
 * </table>
 *
 * @author exeal
 * @date 2010-11-06 Separated from common.hpp.
 */

#ifndef ASCENSION_PLATFORMS_HPP
#define ASCENSION_PLATFORMS_HPP
#include <boost/config.hpp>
#include <boost/predef.h>

#define ASCENSION_CANT_DETECT_PLATFORM()	\
	static_assert(false, "Platform can't detect.")

#define ASCENSION_SUPPORTS_WINDOW_SYSTEM(name) defined( ASCENSION_WINDOW_SYSTEM_##name )
#define ASCENSION_SELECTS_WINDOW_SYSTEM(name) (ASCENSION_SUPPORTS_WINDOW_SYSTEM(name) && ASCENSION_WINDOW_SYSTEM_##name)

#if !ASCENSION_SELECTS_WINDOW_SYSTEM(GTK)		\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(QUARTZ)	\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(QT)		\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(WIN32)	\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(X)
#	if BOOST_OS_MACOS
#		define ASCENSION_WINDOW_SYSTEM_QUARTZ 1
#	elif BOOST_OS_WINDOWS
#		define ASCENSION_WINDOW_SYSTEM_WIN32 1
#	endif
#endif

#if !ASCENSION_SUPPORTS_WINDOW_SYSTEM(QUARTZ) && BOOST_OS_MACOS
#	define ASCENSION_WINDOW_SYSTEM_QUARTZ 0
#endif
#if !ASCENSION_SUPPORTS_WINDOW_SYSTEM(WIN32) && BOOST_OS_WINDOWS
#	define ASCENSION_WINDOW_SYSTEM_WIN32 0
#endif

#ifndef ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS
#	pragma message("Window system selection and support status --")
#	pragma message("  gtkmm: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_GTK))
#	pragma message("  Qt: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_QT))
#	pragma message("  Quartz: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_QUARTZ))
#	pragma message("  Win32: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_WIN32))
#	pragma message("  X Window System: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_X))
#endif // !ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS


#define ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(name) defined( ASCENSION_GRAPHICS_SYSTEM_##name )
#define ASCENSION_SELECTS_GRAPHICS_SYSTEM(name) (ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(name) && ASCENSION_GRAPHICS_SYSTEM_##name)

#if !ASCENSION_SELECTS_GRAPHICS_SYSTEM(CAIRO)				\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)	\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(DIRECT2D)			\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(QT)				\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(WIN32_GDI)		\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(WIN32_GDIPLUS)
#	if ASCENSION_SELECTS_WINDOW_SYSTEM(GTK)
#		define ASCENSION_GRAPHICS_SYSTEM_CAIRO 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(QUARTZ)
#		define ASCENSION_GRAPHICS_SYSTEM_CORE_GRAPHICS 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(QT)
#		define ASCENSION_GRAPHICS_SYSTEM_QT 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(WIN32)
#		define ASCENSION_GRAPHICS_SYSTEM_WIN32_GDI 1
#	endif
#endif

#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CAIRO) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(GTK)
#	define ASCENSION_GRAPHICS_SYSTEM_CAIRO 0
#endif
#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(QUARTZ) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(CORE_GRAPHICS)
#	define ASCENSION_GRAPHICS_SYSTEM_CORE_GRAPHICS 0
#endif
#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(QT) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(QT)
#	define ASCENSION_GRAPHICS_SYSTEM_QT 0
#endif
#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDI) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(WIN32)
#	define ASCENSION_GRAPHICS_SYSTEM_WIN32_GDI 0
#endif

#ifndef ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS
#	pragma message("Graphics system selection and support status --")
#	pragma message("  cairomm: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_CAIRO))
#	pragma message("  Core Graphics: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_CORE_GRAPHICS))
#	pragma message("  Direct2D: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_DIRECT2D))
#	pragma message("  Qt: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_QT))
#	pragma message("  Win32 GDI: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_WIN32_GDI))
#	pragma message("  Win32 GDI+: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_WIN32_GDIPLUS))
#endif // !ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS


#define ASCENSION_SUPPORTS_SHAPING_ENGINE(name) defined( ASCENSION_SHAPING_ENGINE_##name )
#define ASCENSION_SELECTS_SHAPING_ENGINE(name) (ASCENSION_SUPPORTS_SHAPING_ENGINE(name) && ASCENSION_SHAPING_ENGINE_##name)

#if !ASCENSION_SELECTS_SHAPING_ENGINE(CORE_GRAPHICS)	\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(CORE_TEXT)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(DIRECT_WRITE)	\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(HARF_BUZZ)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(PANGO)			\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(QT)			\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(UNISCRIBE)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(WIN32_GDI)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(WIN32_GDIPLUS)
#	if ASCENSION_SELECTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)
#		define ASCENSION_SHAPING_ENGINE_CORE_TEXT 1
#	elif ASCENSION_SELECTS_GRAPHICS_SYSTEM(CAIRO)
#		define ASCENSION_SHAPING_ENGINE_PANGO 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(QT)
#		define ASCENSION_SHAPING_ENGINE_QT 1
#	elif ASCENSION_SELECTS_GRAPHICS_SYSTEM(WIN32_GDI)
#		define ASCENSION_SHAPING_ENGINE_UNISCRIBE 1
#	endif
#endif

#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(CORE_GRAPHICS) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)
#	define ASCENSION_SHAPING_ENGINE_CORE_GRAPHICS 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(CORE_TEXT) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)
#	define ASCENSION_SHAPING_ENGINE_CORE_TEXT 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(PANGO) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CAIRO)
#	define ASCENSION_SHAPING_ENGINE_PANGO 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(QT) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(QT)
#	define ASCENSION_SHAPING_ENGINE_QT 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(UNISCRIBE) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDI)
#	define ASCENSION_SHAPING_ENGINE_UNISCRIBE 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(WIN32_GDI) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDI)
#	define ASCENSION_SHAPING_ENGINE_WIN32_GDI 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(WIN32_GDIPLUS) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDIPLUS)
#	define ASCENSION_SHAPING_ENGINE_WIN32_GDIPLUS 0
#endif

#ifndef ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS
#	pragma message("Shaping engine selection and support status --")
#	pragma message("  Core Text: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_CORE_TEXT))
#	pragma message("  Direct Write: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_DIRECT_WRITE))
#	pragma message("  HarfBuzz: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_HARF_BUZZ))
#	pragma message("  pangomm: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_PANGO))
#	pragma message("  Qt: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_QT))
#	pragma message("  Uniscribe: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_UNISCRIBE))
#	pragma message("  Win32 GDI: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_WIN32_GDI))
#	pragma message("  Win32 GDI+: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_WIN32_GDIPLUS))
#endif // !ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS


// ASCENSION_HAS_CSTDINT and ASCENSION_HAS_UNISTD_H

#if BOOST_OS_AIX
#	define ASCENSION_HAS_CSTDINT
#	define ASCENSION_HAS_UNISTD_H
#elif BOOST_OS_BSD
#	define ASCENSION_HAS_UNISTD_H
#elif BOOST_OS_HPUX
#	if BOOST_COMP_GNUC >= BOOST_VERSION_NUMBER(3, 0, 0)
#		define ASCENSION_CSTDINT
#	endif
#	define ASCENSION_HAS_UNISTD_H
#elif BOOST_OS_LINUX
#	define ASCENSION_HAS_CSTDINT
#	define ASCENSION_HAS_UNISTD_H
#elif BOOST_OS_MACOS
#	define ASCENSION_HAS_UNISTD_H
#elif BOOST_OS_WINDOWS
#	if defined(__MINGW__)
#		define ASCENSION_HAS_CSTDINT
#		define ASCENSION_HAS_UNISTD_H
#	endif
#elif BOOST_OS_SOLARIS
#	define ASCENSION_HAS_UNISTD_H
#endif

#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901)
#	define ASCENSION_HAS_CSTDINT
#elif BOOST_COMP_MSVC >= BOOST_VERSION_NUMBER(10, 0, 0)
#	define ASCENSION_HAS_CSTDINT
#elif defined(ASCENSION_HAS_UNISTD_H)
#	include <unistd.h>
#	if defined(_POSIX_VERSION) && (_POSIX_VERSION >= 200100)
#		define ASCENSION_HAS_STDINT_H
#	endif
#endif

#if defined(ASCENSION_HAS_UNISTD_H) && !defined(BOOST_OS_WINDOWS)
#	define ASCENSION_OS_POSIX BOOST_VERSION_NUMBER_AVAILABLE
#endif


#if BOOST_OS_WINDOWS
#	ifndef _GLIBCXX_USE_WCHAR_T
#		define _GLIBCXX_USE_WCHAR_T 1
#	endif
#	ifndef _GLIBCXX_USE_WSTRING
#		define _GLIBCXX_USE_WSTRING 1
#	endif
#endif // BOOST_OS_WINDOWS

#endif // !ASCENSION_PLATFORMS_HPP
