/**
 * @file platforms.hpp
 * @author exeal
 * @date 2010-11-06 separated from common.hpp
 */

#ifndef ASCENSION_PLATFORMS_HPP
#define ASCENSION_PLATFORMS_HPP
#include <boost/config.hpp>
#include <boost/predef.h>

#define ASCENSION_CANT_DETECT_PLATFORM()	\
	static_assert(false, "Platform can't detect.")

// use BOOST_OS_* instead. however see ASCENSION_OS_POSIX.
#ifdef ASCENSION_ABANDONED_AT_VERSION_08
/*
	Operating system (ASCENSION_OS_*)
	- AIX : AIX
	- BSD4 : Any BSD 4.4 system
	- DARWIN : Darwin OS
	- HPUX : HP-UX
	- LINUX : Linux
	- SOLARIS : Sun Solaris
	- UNIX : Any Unix-like system
	- WINDOWS : Windows
 */
#if defined(__APPLE__) && defined(__GNUC__)
#	define ASCENSION_OS_DARWIN
#	define ASCENSION_OS_BSD4
#	ifdef __LP64__
#		define ASCENSION_OS_DARWIN64
#	else
#		define ASCENSION_OS_DARWIN32
#	endif
#elif defined(__CYGWIN__)
#	define ASCENSION_OS_WINDOWS
#elif defined(_WIN64) || defined(WIN64)
#	define ASCENSION_OS_WIN64
#	define ASCENSION_OS_WIN32
#elif defined(_WIN32) || defined(WIN32)
#	if defined(WINCE) || defined(_WIN32_WCE)
#		define ASCENSION_OS_WINCE
#	else
#		define ASCENSION_OS_WIN32
#	endif
#elif defined(__sun) || defined(sun)
#	define ASCENSION_OS_SOLARIS
#elif defined(__hpux) || defined(hpux)
#	define ASCENSION_OS_HPUX
#elif defined(__linux) || defined(__linux__)
#	define ASCENSION_OS_LINUX
#elif defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__)
#	define ASCENSION_OS_BSD4
#elif defined(_AIX)
#	define ASCENSION_OS_AIX
#elif defined(ANDROID)
/*#	define ASCENSION_OS_ANDROID*/
#elif defined(__HAIKU__)
/*#	define ASCENSION_OS_HAIKU*/
#elif defined(__QNXNTO__)
/*#	define ASCENSION_OS_QNX*/
#elif defined(__SYMBIAN32__)
/*#	define ASCENSION_OS_SYMBIAN*/
#else
#	define ASCENSION_OS_POSIX
#endif

#ifdef ASCENSION_OS_DARWIN
#	define ASCENSION_OS_MACOSX
#	if ASCENSION_OS(DARWIN64)
#		define ASCENSION_OS_MAC64
#	elif ASCENSION_OS(DARWIN32)
#		define ASCENSION_OS_MAC32
#	endif
#endif // ASCENSION_OS_DARWIN

#if defined(ASCENSION_OS_AIX)			\
/*	|| defined(ASCENSION_OS_ANDROID)*/	\
	|| defined(ASCENSION_OS_BSD4)		\
	|| defined(ASCENSION_OS_DARWIN)		\
/*	|| defined(ASCENSION_OS_HAIKU)*/	\
	|| defined(ASCENSION_OS_LINUX)		\
/*	|| defined(ASCENSION_OS_QNX)*/		\
	|| defined(ASCENSION_OS_SOLARIS)	\
/*	|| defined(ASCENSION_OS_SYMBIAN)*/	\
	|| defined(unix)					\
	|| defined(__unix)					\
	|| defined(__unix__)
#	define ASCENSION_OS_UNIX
#endif

#if defined(ASCENSION_OS_WIN64) || defined(ASCENSION_OS_WIN32) || defined(ASCENSION_OS_WINCE)
#	define ASCENSION_OS_WINDOWS
#endif
#endif // ASCENSION_ABANDONED_AT_VERSION_08

/*
	Window system (ASCENSION_WINDOW_SYSTEM_*)
	- GTK : GTK+ 3 (gtkmm 3.x)
	- QUARTZ : Quartz Compositor of Mac OS X
	- QT : Nokia Qt
	- WIN32 : Windows Win32
	- X : X Window System (not supported directly)
 */
#define ASCENSION_SUPPORTS_WINDOW_SYSTEM(name) defined( ASCENSION_WINDOW_SYSTEM_##name )
#define ASCENSION_SELECTS_WINDOW_SYSTEM(name) (ASCENSION_SUPPORTS_WINDOW_SYSTEM(name) && ASCENSION_WINDOW_SYSTEM_##name)

#if !ASCENSION_SELECTS_WINDOW_SYSTEM(GTK)		\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(QUARTZ)	\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(QT)		\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(WIN32)	\
	&& !ASCENSION_SELECTS_WINDOW_SYSTEM(X)
#	if defined(BOOST_OS_MACOS)
#		define ASCENSION_WINDOW_SYSTEM_QUARTZ 1
#	elif defined(BOOST_OS_WINDOWS)
#		define ASCENSION_WINDOW_SYSTEM_WIN32 1
#	endif
#endif

#if !ASCENSION_SUPPORTS_WINDOW_SYSTEM(QUARTZ) && BOOST_OS_MACOS
#	define ASCENSION_WINDOW_SYSTEM_QUARTZ 0
#endif
#if !ASCENSION_SUPPORTS_WINDOW_SYSTEM(WIN32) && BOOST_OS_WINDOWS
#	define ASCENSION_WINDOW_SYSTEM_WIN32 0
#endif

#ifndef ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS
#	pragma message("Window system selection and support status --")
#	pragma message("  gtkmm: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_GTK))
#	pragma message("  Qt: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_QT))
#	pragma message("  Quartz: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_QUARTZ))
#	pragma message("  Win32: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_WIN32))
#	pragma message("  X Window System: " BOOST_STRINGIZE(ASCENSION_WINDOW_SYSTEM_X))
#endif // !ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS


/*
	Graphics system (ASCENSION_GRAPHICS_SYSTEM_*)
	- CAIRO : Cairo
	- CORE_GRAPHICS : Mac OS X Core Graphics
	- DIRECT2D : Windows Direct2D
	- QT : Nokia Qt
	- WIN32_GDI : Windows GDI
	- WIN32_GDIPLUS : Windows GDI+
 */
#define ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(name) defined( ASCENSION_GRAPHICS_SYSTEM_##name )
#define ASCENSION_SELECTS_GRAPHICS_SYSTEM(name) (ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(name) && ASCENSION_GRAPHICS_SYSTEM_##name)

#if !ASCENSION_SELECTS_GRAPHICS_SYSTEM(CAIRO)				\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)	\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(DIRECT2D)			\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(QT)				\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(WIN32_GDI)		\
	&& !ASCENSION_SELECTS_GRAPHICS_SYSTEM(WIN32_GDIPLUS)
#	if ASCENSION_SELECTS_WINDOW_SYSTEM(GTK)
#		define ASCENSION_GRAPHICS_SYSTEM_CAIRO 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(QUARTZ)
#		define ASCENSION_GRAPHICS_SYSTEM_CORE_GRAPHICS 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(QT)
#		define ASCENSION_GRAPHICS_SYSTEM_QT 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(WIN32)
#		define ASCENSION_GRAPHICS_SYSTEM_WIN32_GDI 1
#	endif
#endif

#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CAIRO) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(GTK)
#	define ASCENSION_GRAPHICS_SYSTEM_CAIRO 0
#endif
#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(QUARTZ) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(CORE_GRAPHICS)
#	define ASCENSION_GRAPHICS_SYSTEM_CORE_GRAPHICS 0
#endif
#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(QT) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(QT)
#	define ASCENSION_GRAPHICS_SYSTEM_QT 0
#endif
#if !ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDI) && ASCENSION_SUPPORTS_WINDOW_SYSTEM(WIN32)
#	define ASCENSION_GRAPHICS_SYSTEM_WIN32_GDI 0
#endif

#ifndef ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS
#	pragma message("Graphics system selection and support status --")
#	pragma message("  cairomm: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_CAIRO))
#	pragma message("  Core Graphics: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_CORE_GRAPHICS))
#	pragma message("  Direct2D: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_DIRECT2D))
#	pragma message("  Qt: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_QT))
#	pragma message("  Win32 GDI: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_WIN32_GDI))
#	pragma message("  Win32 GDI+: " BOOST_STRINGIZE(ASCENSION_GRAPHICS_SYSTEM_WIN32_GDIPLUS))
#endif // !ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS


/*
	Text/Glyph shaping engine (ASCENSION_SHAPING_ENGINE_*)
	- CORE_GRAPHICS : Mac OS X Core Graphics
	- CORE_TEXT : Mac OS X Core Text
	- DIRECT_WRITE : Windows DirectWrite
	- HARFBUZZ : HarfBuzz
	- PANGO : Pango
	- QT : Nokia Qt
	- UNISCRIBE : Windows Uniscribe
	- WIN32_GDI : Windows GDI
	- WIN32_GDIPLUS : Windows GDI+
 */
#define ASCENSION_SUPPORTS_SHAPING_ENGINE(name) defined( ASCENSION_SHAPING_ENGINE_##name )
#define ASCENSION_SELECTS_SHAPING_ENGINE(name) (ASCENSION_SUPPORTS_SHAPING_ENGINE(name) && ASCENSION_SHAPING_ENGINE_##name)

#if !ASCENSION_SELECTS_SHAPING_ENGINE(CORE_GRAPHICS)	\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(CORE_TEXT)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(DIRECT_WRITE)	\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(HARF_BUZZ)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(PANGO)			\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(QT)			\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(UNISCRIBE)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(WIN32_GDI)		\
	&& !ASCENSION_SELECTS_SHAPING_ENGINE(WIN32_GDIPLUS)
#	if ASCENSION_SELECTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)
#		define ASCENSION_SHAPING_ENGINE_CORE_TEXT 1
#	elif ASCENSION_SELECTS_GRAPHICS_SYSTEM(CAIRO)
#		define ASCENSION_SHAPING_ENGINE_PANGO 1
#	elif ASCENSION_SELECTS_WINDOW_SYSTEM(QT)
#		define ASCENSION_SHAPING_ENGINE_QT 1
#	elif ASCENSION_SELECTS_GRAPHICS_SYSTEM(WIN32_GDI)
#		define ASCENSION_SHAPING_ENGINE_UNISCRIBE 1
#	endif
#endif

#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(CORE_GRAPHICS) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)
#	define ASCENSION_SHAPING_ENGINE_CORE_GRAPHICS 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(CORE_TEXT) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CORE_GRAPHICS)
#	define ASCENSION_SHAPING_ENGINE_CORE_TEXT 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(PANGO) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(CAIRO)
#	define ASCENSION_SHAPING_ENGINE_PANGO 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(QT) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(QT)
#	define ASCENSION_SHAPING_ENGINE_QT 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(UNISCRIBE) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDI)
#	define ASCENSION_SHAPING_ENGINE_UNISCRIBE 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(WIN32_GDI) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDI)
#	define ASCENSION_SHAPING_ENGINE_WIN32_GDI 0
#endif
#if !ASCENSION_SUPPORTS_SHAPING_ENGINE(WIN32_GDIPLUS) && ASCENSION_SUPPORTS_GRAPHICS_SYSTEM(WIN32_GDIPLUS)
#	define ASCENSION_SHAPING_ENGINE_WIN32_GDIPLUS 0
#endif

#ifndef ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS
#	pragma message("Shaping engine selection and support status --")
#	pragma message("  Core Text: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_CORE_TEXT))
#	pragma message("  Direct Write: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_DIRECT_WRITE))
#	pragma message("  HarfBuzz: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_HARF_BUZZ))
#	pragma message("  pangomm: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_PANGO))
#	pragma message("  Qt: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_QT))
#	pragma message("  Uniscribe: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_UNISCRIBE))
#	pragma message("  Win32 GDI: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_WIN32_GDI))
#	pragma message("  Win32 GDI+: " BOOST_STRINGIZE(ASCENSION_SHAPING_ENGINE_WIN32_GDIPLUS))
#endif // !ASCENSION_NO_PLATFORM_SELECTION_DIAGNOSIS


// use BOOST_COMP_* instead.
#ifdef ASCENSION_ABANDONED_AT_VERSION_08
/*
	!DEPRECATED! I can't list all compilers!
	C++ compiler (ASCENSION_COMPILER_*)
	- CLANG : Clang
	- COMEAU : Comeau C++
	- GCC : GNU C++
	- MSVC : Microsoft Visual C++
	- WATCOM : Watcom C++
 */
#if defined(BOOST_CLANG)
#	define ASCENSION_COMPILER_CLANG
#elif defined(__COMO__)
#	define ASCENSION_COMPILER_COMEAU
#elif defined(BOOST_GCC)
#	define ASCENSION_COMPILER_GCC
#elif defined(BOOST_MSVC)
#	define ASCENSION_COMPILER_MSVC
#elif defined(__WATCOMC__)
#	define ASCENSION_COMPILER_WATCOM
#endif
#endif // ASCENSION_ABANDONED_AT_VERSION_08


// ASCENSION_FASTCALL

#if defined(__i386__) || defined(_WIN32) || defined(_WIN32_WCE)
#	if defined(BOOST_COMP_GNUC) && (BOOST_COMP_GNUC >= BOOST_VERSION_NUMBER(3, 3, 2))
#		define ASCENSION_FASTCALL __attribute__((regparm(3)))
#	elif defined(BOOST_COMP_MSVC) && (BOOST_COMP_MSVC > BOOST_VERSION_NUMBER(7, 0, 0))
#		define ASCENSION_FASTCALL __fastcall
#	endif
#endif
#ifndef ASCENSION_FASTCALL
#	define ASCENSION_FASTCALL
#endif


// ASCENSION_HAS_CSTDINT and ASCENSION_HAS_UNISTD_H

#if defined(BOOST_OS_AIX)
#	define ASCENSION_HAS_CSTDINT
#	define ASCENSION_HAS_UNISTD_H
#elif defined(BOOST_OS_BSD)
#	define ASCENSION_HAS_UNISTD_H
#elif defined(BOOST_OS_HPUX)
#	if defined(BOOST_COMP_GNUC) && (BOOST_COMP_GNUC >= BOOST_VERSION_NUMBER(3, 0, 0))
#		define ASCENSION_CSTDINT
#	endif
#	define ASCENSION_HAS_UNISTD_H
#elif defined(BOOST_OS_LINUX)
#	define ASCENSION_HAS_CSTDINT
#	define ASCENSION_HAS_UNISTD_H
#elif defined(BOOST_OS_MACOS)
#	define ASCENSION_HAS_UNISTD_H
#elif defined(BOOST_OS_WINDOWS)
#	if defined(__MINGW__)
#		define ASCENSION_HAS_CSTDINT
#		define ASCENSION_HAS_UNISTD_H
#	endif
#elif defined(BOOST_OS_SOLARIS)
#	define ASCENSION_HAS_UNISTD_H
#endif

#if defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901)
#	define ASCENSION_HAS_CSTDINT
#elif defined(BOOST_COMP_MSVC) && (BOOST_COMP_MSVC >= BOOST_VERSION_NUMBER(10, 0, 0))
#	define ASCENSION_HAS_CSTDINT
#elif defined(ASCENSION_HAS_UNISTD_H)
#	include <unistd.h>
#	if defined(_POSIX_VERSION) && (_POSIX_VERSION >= 200100)
#		define ASCENSION_HAS_STDINT_H
#	endif
#endif

#if defined(ASCENSION_HAS_UNISTD_H) && !defined(BOOST_OS_WINDOWS)
#	define ASCENSION_OS_POSIX
#endif


#ifdef BOOST_OS_WINDOWS
#	ifndef _GLIBCXX_USE_WCHAR_T
#		define _GLIBCXX_USE_WCHAR_T 1
#	endif
#	ifndef _GLIBCXX_USE_WSTRING
#		define _GLIBCXX_USE_WSTRING 1
#	endif
#endif // BOOST_OS_WINDOWS

#ifdef BOOST_OS_WINDOWS
#	define ASCENSION_USE_INTRINSIC_WCHAR_T
#endif

#endif // !ASCENSION_PLATFORMS_HPP
