//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Alpha.rc
//
#define IDR_MENU                        101
#define IDR_MENU_SEARCHOPTION           102
#define IDR_ICONS                       111
#define IDB_BMP_LOGO                    153
#define IDR_ICON_NARROWING              154
#define IDR_ICON_TEMPMACRODEFINING      155
#define IDR_ICON_TEMPMACROPAUSING       156
#define IDR_CODEPAGE_NAME_TABLE         172
#define IDC_STATUSBAR                   201
#define IDC_TOOLBAR                     202
#define IDC_BUFFERBAR                   204
#define IDC_BUFFERBARPAGER              205
#define IDD_DLG_OPENFILE                501
#define IDD_DLG_SAVEFILE                502
#define IDD_DLG_SEARCH                  503
#define IDD_DLG_ABOUT                   504
#define IDD_DLG_CODEPAGES               505
#define IDD_DLG_GOTOLINE                507
#define IDD_DLG_EXECUTECOMMAND          508
#define IDD_DLG_BOOKMARKS               509
#define IDD_DLG_SELECTLANGUAGE          510
#define IDD_DLG_SAVESOMEBUFFERS         511
#define IDD_DLG_FILENEWWITHFORMAT       512
#define IDD_DLG_ABBREVIATIONS           513
#define IDD_DLG_NEWABBREV               514
#define IDD_DLG_BUFFERLIST              515
#define IDD_DLG_LOADTEMPMACRO           516
#define IDD_DLG_SAVETEMPMACRO           517
#define IDD_DLG_PAGESETUPTEMPLATE       518
#define COMMAND_START                   1000
#define CMD_FILE_NEW                    1000
#define IDC_TAB_VIEWS                   1001
#define CMD_FILE_NEWWITHFORMAT          1001
#define IDC_TAB_VARIABLES               1002
#define CMD_FILE_OPEN                   1002
#define IDC_TAB_KEYWORD                 1003
#define CMD_FILE_CLOSE                  1003
#define IDC_TAB_SEARCHTYPE              1004
#define CMD_FILE_CLOSEALL               1004
#define CMD_FILE_SAVE                   1005
#define CMD_FILE_SAVEAS                 1006
#define CMD_FILE_SAVEALL                1007
#define CMD_FILE_REOPEN                 1008
#define CMD_FILE_REOPENWITHCODEPAGE     1009
#define CMD_FILE_EXIT                   1010
#define CMD_FILE_SENDMAIL               1016
#define CMD_FILE_CLOSEOTHERS            1017
#define CMD_FILE_PRINT                  1018
#define CMD_FILE_PRINTSETUP             1019
#define CMD_FILE_PRINTPREVIEW           1020
#define IDC_COMBO_ENCODING              1101
#define IDC_COMBO_NEWLINE               1102
#define IDC_COMBO_FINDWHAT              1103
#define IDC_COMBO_REPLACEWITH           1104
#define IDC_COMBO_MACROS                1105
#define IDC_COMBO_COMMAND               1106
#define IDC_COMBO_DOCTYPENAMES          1107
#define IDC_COMBO_SEARCHTYPE            1108
#define IDC_COMBO_WHOLEMATCH            1109
#define IDC_COMBO_COLLATIONWEIGHT       1110
#define IDC_CHK_IGNORECASE              1201
#define IDC_CHK_CANONICALEQUIVALENTS    1202
#define IDC_CHK_AUTOCLOSE               1203
#define IDC_CHK_SAVESELECTION           1204
#define IDC_CHK_GETCONSOLE              1205
#define IDC_CHK_USEUNICODEFORINPUT      1206
#define IDC_CHK_SHOWALLFILES            1207
#define IDC_CHK_SHIFT                   1208
#define IDC_CHK_LINENUMBERS             1209
#define IDC_CHK_HEADER                  1210
#define IDC_RADIO_SELECTION             1301
#define IDC_RADIO_WHOLEFILE             1302
#define IDC_CHECK2                      1317
#define IDC_LINK_HOMEPAGE               1401
#define IDC_LINK_SELECTALL              1402
#define IDC_LINK_CLEARALL               1403
#define IDC_LINK_SOURCEFORGE            1404
#define IDC_BTN_BROWSE                  1501
#define IDC_BTN_ADD                     1502
#define IDC_BTN_DELETE                  1503
#define IDC_BTN_EXECUTE                 1504
#define IDC_BTN_SENDEOS                 1505
#define IDC_BTN_UPDATE                  1506
#define IDC_BTN_CLEAR                   1507
#define IDC_EDIT_FILENAME               1601
#define IDC_EDIT_DESTPATH               1602
#define IDC_EDIT_LINENUMBER             1603
#define IDC_EDIT_INPUT                  1604
#define IDC_EDIT_OUTPUT                 1605
#define IDC_SPIN_LINENUMBER             1701
#define IDC_STATIC_1                    1801
#define IDC_STATIC_2                    1802
#define IDC_STATIC_3                    1803
#define IDC_STATIC_4                    1804
#define IDC_STATIC_5                    1805
#define IDC_STATIC_PROMPT               1806
#define CMD_FILE_TOP                    1900
#define IDC_LIST_CODEPAGES              1901
#define CMD_FILE_MRU                    1901
#define CMD_FILE_OPERATE                1902
#define IDC_LIST_BOOKMARKS              1902
#define IDC_LIST_SCRIPTENGINES          1903
#define IDC_LIST_BUFFERS                1904
#define IDC_LIST_ABBREVIATIONS          1905
#define IDC_LIST_MACROS                 1906
#define CMD_EDIT_DELETE                 2000
#define IDC_TREE_OUTLINE                2001
#define CMD_EDIT_BACKSPACE              2001
#define IDC_TREE_COMMANDS               2002
#define CMD_EDIT_DELETETONEXTWORD       2002
#define IDC_TREE_ACTIVEDOCUMENTS        2003
#define CMD_EDIT_DELETETOPREVWORD       2003
#define CMD_EDIT_DELETELINE             2004
#define CMD_EDIT_INSERTPREVLINE         2005
#define CMD_EDIT_BREAK                  2006
#define CMD_EDIT_UNDO                   2007
#define CMD_EDIT_REDO                   2008
#define CMD_EDIT_CUT                    2009
#define CMD_EDIT_COPY                   2010
#define CMD_EDIT_PASTE                  2011
#define CMD_EDIT_INSERTTAB              2012
#define CMD_EDIT_DELETETAB              2013
#define CMD_EDIT_TABIFY                 2014
#define CMD_EDIT_UNTABIFY               2015
#define CMD_EDIT_CHARTOCODEPOINT        2016
#define CMD_EDIT_CODEPOINTTOCHAR        2017
#define CMD_EDIT_RECOMPOSE              2024
#define CMD_EDIT_TOGGLEOVERTYPEMODE     2025
#define CMD_EDIT_OPENCANDIDATEWINDOW    2026
#define CMD_EDIT_HOME                   2027
#define CMD_EDIT_END                    2028
#define CMD_EDIT_LINEHOME               2029
#define CMD_EDIT_LINEEND                2030
#define CMD_EDIT_CHARNEXT               2031
#define CMD_EDIT_CHARPREV               2032
#define CMD_EDIT_WORDENDNEXT            2033
#define CMD_EDIT_WORDENDPREV            2034
#define CMD_EDIT_WORDNEXT               2035
#define CMD_EDIT_WORDPREV               2036
#define CMD_EDIT_LINEDOWN               2037
#define CMD_EDIT_LINEUP                 2038
#define CMD_EDIT_PAGEDOWN               2039
#define CMD_EDIT_PAGEUP                 2040
#define CMD_EDIT_HOMEEXTEND             2041
#define CMD_EDIT_ENDEXTEND              2042
#define CMD_EDIT_LINEHOMEEXTEND         2043
#define CMD_EDIT_LINEENDEXTEND          2044
#define CMD_EDIT_CHARNEXTEXTEND         2045
#define CMD_EDIT_CHARPREVEXTEND         2046
#define CMD_EDIT_WORDENDNEXTEXTEND      2047
#define CMD_EDIT_WORDENDPREVEXTEND      2048
#define CMD_EDIT_WORDNEXTEXTEND         2049
#define CMD_EDIT_WORDPREVEXTEND         2050
#define CMD_EDIT_LINEDOWNEXTEND         2051
#define CMD_EDIT_LINEUPEXTEND           2052
#define CMD_EDIT_PAGEDOWNEXTEND         2053
#define CMD_EDIT_PAGEUPEXTEND           2054
#define CMD_EDIT_SELECTALL              2055
#define CMD_EDIT_SELECTCURRENTWORD      2056
#define CMD_EDIT_CANCELSELECTION        2057
#define CMD_EDIT_SCROLLHOME             2058
#define CMD_EDIT_SCROLLEND              2059
#define CMD_EDIT_SCROLLLINEDOWN         2060
#define CMD_EDIT_SCROLLLINEUP           2061
#define CMD_EDIT_SCROLLPAGEDOWN         2062
#define CMD_EDIT_SCROLLPAGEUP           2063
#define CMD_EDIT_SCROLLCOLUMNNEXT       2064
#define CMD_EDIT_SCROLLCOLUMNPREV       2065
#define CMD_EDIT_ENSURECARETCENTER      2066
#define CMD_EDIT_ENSURECARETVISIBLE     2067
#define CMD_EDIT_ROWCHARNEXT            2070
#define CMD_EDIT_ROWCHARPREV            2071
#define CMD_EDIT_ROWLINEDOWN            2072
#define CMD_EDIT_ROWLINEUP              2073
#define CMD_EDIT_ROWLINEEND             2074
#define CMD_EDIT_ROWLINEHOME            2075
#define CMD_EDIT_ROWWORDNEXT            2076
#define CMD_EDIT_ROWWORDPREV            2077
#define CMD_EDIT_ROWWORDENDNEXT         2078
#define CMD_EDIT_ROWWORDENDPREV         2079
#define CMD_EDIT_PASTEFROMCLIPBOARDRING 2080
#define CMD_EDIT_CHARFROMABOVELINE      2081
#define CMD_EDIT_CHARFROMBELOWLINE      2082
#define CMD_EDIT_TRANSPOSELINES         2083
#define CMD_EDIT_TRANSPOSECHARS         2084
#define CMD_EDIT_TRANSPOSEWORDS         2085
#define CMD_EDIT_SHOWABBREVIATIONDLG    2086
#define CMD_EDIT_FIRSTCHAR              2090
#define CMD_EDIT_LASTCHAR               2091
#define CMD_EDIT_FIRSTCHAREXTEND        2092
#define CMD_EDIT_LASTCHAREXTEND         2093
#define CMD_EDIT_FIRSTCHARORLINEHOME    2094
#define CMD_EDIT_LASTCHARORLINEEND      2095
#define CMD_EDIT_FIRSTCHARORLINEHOMEEXTEND 2096
#define CMD_EDIT_LASTCHARORLINEENDEXTEND 2097
#define CMD_EDIT_NARROWTOSELECTION      2098
#define CMD_EDIT_WIDEN                  2099
#define CMD_EDIT_TOP                    2900
#define CMD_EDIT_ADVANCED               2901
#define CMD_EDIT_INSERTUNICODECTRLS     2902
#define CMD_EDIT_INSERTUNICODEWSS       2903
#define CMD_SEARCH_FIND                 3000
#define CMD_SEARCH_FINDNEXT             3001
#define CMD_SEARCH_FINDPREV             3002
#define CMD_SEARCH_REPLACEANDNEXT       3004
#define CMD_SEARCH_REPLACEALL           3005
#define CMD_SEARCH_BOOKMARKALL          3006
#define CMD_SEARCH_REVOKEMARK           3007
#define CMD_SEARCH_GOTOLINE             3008
#define CMD_SEARCH_TOGGLEBOOKMARK       3009
#define CMD_SEARCH_NEXTBOOKMARK         3010
#define CMD_SEARCH_PREVBOOKMARK         3011
#define CMD_SEARCH_CLEARBOOKMARKS       3012
#define CMD_SEARCH_MANAGEBOOKMARKS      3013
#define CMD_SEARCH_GOTOMATCHBRACKET     3014
#define CMD_SEARCH_EXTENDTOMATCHBRACKET 3015
#define CMD_SEARCH_INCREMENTALSEARCH    3016
#define CMD_SEARCH_INCREMENTALSEARCHR   3017
#define CMD_SEARCH_INCREMENTALSEARCHRF  3018
#define CMD_SEARCH_INCREMENTALSEARCHRR  3019
#define CMD_SEARCH_INCREMENTALSEARCHMF  3020
#define CMD_SEARCH_INCREMENTALSEARCHMR  3021
#define CMD_SEARCH_FINDFILES            3022
#define CMD_SEARCH_SEARCHMULTIPLEFILES  3023
#define CMD_SEARCH_REPLACEMULTIPLEFILES 3024
#define CMD_SEARCH_TOP                  3900
#define CMD_SEARCH_BOOKMARKS            3901
#define CMD_VIEW_TOOLBAR                4000
#define CMD_VIEW_STATUSBAR              4001
#define CMD_VIEW_WRAPNO                 4002
#define CMD_VIEW_WRAPBYSPECIFIEDWIDTH   4003
#define CMD_VIEW_WRAPBYWINDOWWIDTH      4004
#define CMD_VIEW_REFRESH                4005
#define CMD_VIEW_NEXTBUFFER             4007
#define CMD_VIEW_PREVBUFFER             4008
#define CMD_VIEW_BUFFERBAR              4009
#define CMD_VIEW_BUFFERLIST_START       4100
#define CMD_VIEW_BUFFERLIST_END         4800
#define CMD_VIEW_TOP                    4900
#define CMD_VIEW_BUFFERS                4901
#define CMD_MACRO_DEFINE                5000
#define CMD_MACRO_EXECUTE               5001
#define CMD_MACRO_APPEND                5002
#define CMD_MACRO_PAUSERESTART          5003
#define CMD_MACRO_INSERTQUERY           5004
#define CMD_MACRO_ABORT                 5005
#define CMD_MACRO_SAVEAS                5006
#define CMD_MACRO_LOAD                  5007
#define CMD_MACRO_TOP                   5900
#define CMD_MACRO_SCRIPTS               5901
#define CMD_TOOL_COMMONOPTION           6000
#define CMD_TOOL_DOCTYPEOPTION          6001
#define CMD_TOOL_FONT                   6002
#define CMD_TOOL_EXECUTE                6003
#define CMD_TOOL_EXECUTECOMMAND         6004
#define CMD_TOOL_TOP                    6900
#define CMD_TOOL_APPDOCTYPES            6901
#define CMD_WINDOW_SPLITNS              7000
#define CMD_WINDOW_SPLITWE              7001
#define CMD_WINDOW_UNSPLITACTIVE        7002
#define CMD_WINDOW_UNSPLITOTHERS        7003
#define CMD_WINDOW_NEXTPANE             7004
#define CMD_WINDOW_PREVPANE             7005
#define CMD_WINDOW_TOPMOSTALWAYS        7006
#define CMD_WINDOW_TOP                  7900
#define CMD_HELP_ABOUT                  8000
#define CMD_HELP_TOP                    8900
#define CMD_SPECIAL_ILLEGAL2STROKE      9000
#define CMD_SPECIAL_WAITFOR2NDKEYS      9001
#define CMD_SPECIAL_DISPATCHCHARINPUT   9002
#define COMMAND_END                     10000
#define CMD_FILE_MRULIST_START          11000
#define CMD_FILE_MRULIST_END            11100
#define CMD_FILE_DOCTYPELIST_START      11100
#define CMD_FILE_DOCTYPELIST_END        11200
#define CMD_TOOL_DOCTYPELIST_START      11200
#define CMD_TOOL_DOCTYPELIST_END        11300
#define CMD_EDIT_PLUGINLIST_START       11300
#define CMD_EDIT_PLUGINLIST_END         11500
#define GENERAL_MESSAGE_START           20000
#define MSG_DIALOG__WHOLE_GRAPHEME_MATCH 20000
#define MSG_DIALOG__WHOLE_WORD_MATCH    20001
#define MSG_DIALOG__LITERAL_SEARCH      20004
#define MSG_DIALOG__REGEXP_SEARCH       20005
#define MSG_DIALOG__MIGEMO_SEARCH       20006
#define MSG_DIALOG__BUFFERBAR_CAPTION   20007
#define MSG_DIALOG__ABBREVIATION        20008
#define MSG_DIALOG__EXPANDED_ABBREVIATION 20009
#define MSG_DIALOG__BOOKMARKED_LINE     20010
#define MSG_DIALOG__BOOKMARKED_POSITION 20011
#define MSG_DIALOG__LINE_NUMBER_RANGE   20012
#define MSG_DIALOG__SELECT_ALL          20013
#define MSG_DIALOG__UNSELECT_ALL        20014
#define MSG_DIALOG__SELECT_DIRECTORY    20015
#define MSG_DIALOG__FILE_OPERATION      20016
#define MSG_DIALOG__RENAME_FILE         20017
#define MSG_DIALOG__COPY_FILE           20018
#define MSG_DIALOG__MOVE_FILE           20019
#define MSG_DIALOG__KEEP_NEWLINE        20020
#define MSG_DIALOG__SAVE_FILE_FILTER    20023
#define MSG_IO__FAILED_TO_DETECT_ENCODE 20100
#define MSG_IO__INVALID_ENCODING        20101
#define MSG_IO__INVALID_NEWLINE         20102
#define MSG_IO__UNCONVERTABLE_UCS_CHAR  20103
#define MSG_IO__UNCONVERTABLE_NATIVE_CHAR 20104
#define MSG_IO__HUGE_FILE               20105
#define MSG_IO__FAILED_TO_WRITE_FOR_READONLY 20106
#define MSG_IO__FAILED_TO_RESOLVE_SHORTCUT 20107
#define MSG_IO__CANNOT_OPEN_FILE        20108
#define MSG_IO__CANNOT_CREATE_TEMP_FILE 20109
#define MSG_IO__LOST_DISK_FILE          20110
#define MSG_DIALOG__DEFAULT_OPENFILE_FILTER 20122
#define MSG_BUFFER__BUFFER_IS_DIRTY     20200
#define MSG_BUFFER__CONFIRM_REOPEN      20201
#define MSG_BUFFER__CONFIRM_REOPEN_EVEN_IF_DIRTY 20202
#define MSG_BUFFER__FAILED_TO_SEND_TO_MAILER 20203
#define MSG_BUFFER__UNTITLED            20204
#define MSG_BUFFER__FILE_IS_MODIFIED_AND_REOPEN 20205
#define MSG_BUFFER__FILE_IS_MODIFIED_AND_SAVE 20206
#define MSG_BUFFER__FILE_IS_MODIFIED_AND_EDIT 20207
#define MSG_BUFFER__SAVING_FILE_IS_OPENED 20208
#define MSG_SCRIPT__SCRIPT_ERROR_DIALOG 20300
#define MSG_SCRIPT__UNSAFE_ACTIVEX_CAUTION 20301
#define MSG_SCRIPT__INVALID_LANGUAGE_NAME 20302
#define MSG_SCRIPT__FAILED_TO_OPEN_MACRO_SCRIPT 20303
#define MSG_STATUS__READ_ONLY_CAPTION   20400
#define MSG_STATUS__TEMP_MACRO_DEFINING 20401
#define MSG_STATUS__TEMP_MACRO_PAUSING  20402
#define MSG_STATUS__NARROWING           20403
#define MSG_STATUS__DEBUGGING           20404
#define MSG_STATUS__INSERT_MODE         20405
#define MSG_STATUS__OVERTYPE_MODE       20406
#define MSG_STATUS__CARET_POSITION      20407
#define MSG_STATUS__CAN_EXPAND_ABBREV   20408
#define MSG_STATUS__LOADING_FILE        20409
#define MSG_STATUS__WAITING_FOR_2ND_KEYS 20410
#define MSG_STATUS__INVALID_2STROKE_COMBINATION 20411
#define MSG_STATUS__ISEARCH             20412
#define MSG_STATUS__ISEARCH_EMPTY_PATTERN 20413
#define MSG_STATUS__ISEARCH_BAD_PATTERN 20414
#define MSG_STATUS__ISEARCH_NOT_FOUND   20415
#define MSG_STATUS__RISEARCH            20416
#define MSG_STATUS__RISEARCH_NOT_FOUND  20417
#define MSG_STATUS__RISEARCH_BAD_PATTERN 20418
#define MSG_STATUS__RISEARCH_EMPTY_PATTERN 20419
#define MSG_STATUS__MATCH_BRACKET_OUT_OF_VIEW 20420
#define MSG_STATUS__INVOKABLE_LINK_POPUP 20421
#define MSG_ERROR__EXE_NOT_REGISTERED   20500
#define MSG_ERROR__FAILED_TO_RUN_EXE    20501
#define MSG_ERROR__UNSUPPORTED_OS_VERSION 20502
#define MSG_ERROR__DUPLICATE_ABBREV     20503
#define MSG_ERROR__REGEX_UNKNOWN_ERROR  20504
#define MSG_ERROR__MIGEMO_UNKNOWN_ERROR 20505
#define MSG_ERROR__PROHIBITED_FOR_MACRO_DEFINING 20506
#define MSG_ERROR__FAILED_TO_LOAD_TEMP_MACRO 20507
#define MSG_ERROR__FAILED_TO_LOAD_SOMETHING 20508
#define MSG_ERROR__OUT_OF_MEMORY        20509
#define MSG_SEARCH__PATTERN_NOT_FOUND   20600
#define MSG_SEARCH__REPLACE_DONE        20601
#define MSG_SEARCH__REGEX_IS_INAVAILABLE 20602
#define MSG_SEARCH__INVALID_REGEX_PATTERN 20603
#define MSG_SEARCH__BAD_REGEX_PATTERN_START 20604
#define MSG_SEARCH__BAD_REGEX_PATTERN_END 20617
#define MSG_OTHER__EMPTY_MENU_CAPTION   20700
#define MSG_OTHER__UNKNOWN              20701
#define MSG_OTHER__NOT_OBTAINED         20702
#define MSG_OTHER__TEMPORARY_MACRO_QUERY 20703
#define MSG_OTHER__NONE                 20704

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        174
#define _APS_NEXT_COMMAND_VALUE         40048
#define _APS_NEXT_CONTROL_VALUE         1318
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
